// Generated by CoffeeScript 1.6.3
(function() {
  var PigLatin;

  exports.PigLatin = PigLatin = (function() {
    function PigLatin(buffer) {
      this.buffer = buffer;
    }

    PigLatin.prototype.convert = function() {
      var pig_latin_words;
      pig_latin_words = this.buffer.split(/\ +/).map(function(word) {
        var ay, lword, m, pword;
        lword = word.toLowerCase();
        m = lword.match(/^([^aeiou]*)(.*)$/ || (function() {
          throw 'error';
        })());
        if (m[1].length === 0) {
          ay = 'way';
        } else {
          ay = 'ay';
        }
        pword = m[2] + m[1] + ay;
        if (word.match(/^[A-Z]/)) {
          pword = pword[0].toUpperCase() + pword.slice(1);
        }
        return pword;
      });
      return pig_latin_words.join(' ');
    };

    return PigLatin;

  })();

}).call(this);
