// Generated by CoffeeScript 1.6.3
(function() {
  var Latin, Pig;

  exports.Pig || (exports.Pig = Pig = (function() {
    function Pig() {}

    return Pig;

  })());

  exports.Pig.Latin = Latin = (function() {
    function Latin(buffer) {
      this.buffer = buffer;
    }

    Latin.prototype.convert = function() {
      var pig_latin_words;
      pig_latin_words = this.buffer.split(/\ +/).map(function(word) {
        var ay, lword, m, pword;
        lword = word.toLowerCase();
        m = lword.match(/^([^aeiou]*)(.*)$/ || (function() {
          throw 'error';
        })());
        if (m[1].length === 0) {
          ay = 'way';
        } else {
          ay = 'ay';
        }
        pword = m[2] + m[1] + ay;
        if (word.match(/^[A-Z]/)) {
          pword = pword[0].toUpperCase() + pword.slice(1);
        }
        return pword;
      });
      return pig_latin_words.join(' ');
    };

    return Latin;

  })();

}).call(this);
